name: Need
description: Stakeholder or customer need
labels: ["type:need"]

body:
- type: textarea
  attributes:
    label: Need Description
    description: Raw request or problem from stakeholder

- type: dropdown
  attributes:
    label: Status
    options:
      - Draft
      - Under Analysis
      - Refined
      - Ready
      - Rejected

- type: dropdown
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
      
- type: dropdown
  attributes:
    label: Difficulty
    options:
      - Low
      - Medium
      - High

- type: input
  attributes:
    label: Target Version

- type: input
  attributes:
    label: Cost

- type: input
  attributes:
    label: Derived From (EPIC)
    description: Example EPIC#01
