name: Need
description: Stakeholder or customer need
labels: ["type:need"]

body:
- type: textarea
  attributes:
    label: Need Description
    description: Raw request or problem from stakeholder

- type: dropdown
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low

- type: input
  attributes:
    label: Derived From (EPIC)
    description: Example EPIC-001
