name: System Requirement
description: Non-functional requirement
labels: ["type:sr"]

body:
- type: dropdown
  attributes:
    label: Caterory
    options:
      - Security
      - Performance
      - Reliability
      - Usability
      - Maintainability

- type: textarea
  attributes:
    label: Requirement Description

- type: input
  attributes:
    label: Constraints

- type: input
  attributes:
    label: Derived From
    description: Example NEED-001 or FEAT-001
