name: Use Case
description: Functional behavior of the system
labels: ["type:use-case"]

body:
- type: input
  attributes:
    label: UC ID

body:
- type: input
  attributes:
    label: UC Name

    - type: textarea
  attributes:
    label: Description

- type: input
  attributes:
    label: Primary Actor

- type: textarea
  attributes:
    label: Stakeholders & Interests
    
- type: input
  attributes:
    label: Precondition

- type: input
  attributes:
    label: Trigger

- type: textarea
  attributes:
    label: Main Flow

- type: textarea
  attributes:
    label: Alternate / Exception Flow

- type: input
  attributes:
    label: Inputs

- type: input
  attributes:
    label: Outputs

- type: input
  attributes:
    label: Related Features

- type: input
  attributes:
    label: Notes / Constraints

- type: dropdown
  attributes:
    label: Status
    options:
      - Draft
      - Approved
      - Implemented
      - Tested
      - Done

- type: dropdown
  attributes:
    label: Priority
    options:
      - High
      - Medium
      - Low
